### ISSUE TITLE
Break out middleware to enable in-app hosting

### ISSUE THREAD

**Issue by joelpurra** [tfrce/social-buttons-server#4]
Instead of starting an Express server in the same file as the counter logic, perhaps they could be separated?

I would like to host the counter logic as a part of another node/Express server -- and instead of having the user make a cross-domain request, I'd prefer if the primary domain could host the counter logic as middleware. (Without using a proxy or similar solution.)

**Comment by joelpurra** [comment]
Needed in-app hosting of the social buttons server in one of my projects, so now the work to break out the server file has ben done but not yet published.

1. Broke out the server as middleware, so it can be both used in a standalone-server and hosted inside another Express app.
1. Broke out the counter fetching logic so it can be used outside of Express as well -- most likely in another http server.
1. Prepared the middleware and counter logic for testing (not yet implemented) by making them into classes.
1. Fixed Google Plus counts.
1. Added some in-memory caching per network and url.
1. Prevented (most cases of) accidental fetching of the same network/url count in parallel when clients request them too fast.
1. Made the logger an option, so it can be swapped out if necessary.

All of this makes it a non-trivial patch. Should add that it would be much preferable if they were maintained as *three* different git repos/node packages. I could fork this project plus create two new projects and then let you backport these fixes. A concern would then be that the two sub-projects would be published on npmjs.org by me, where they packages aren't namespaced.

Would it still be of interest to Taskforce to retain control and commit to maintaining these three projects?

**Comment by thomasdavis** [comment]
hey @joelpurra, maybe we should just create a new org for the service -> I'm sitting in this chat -> https://gitter.im/tfrce/social-buttons-server

**Comment by joelpurra** [comment]
@thomasdavis: yes, that might be a good option.

While I haven't shopped around for similar server-side social network button count lookup packages for node.js, I definitely see potential in software like this to be extended and used by quite a few privacy-aware developers.

**Comment by joelpurra** [comment]
@thomasdavis: glad you suggested starting a new organization -- had fun starting it! The name is **Meddelare**, a Swedish word for co-sharer (med-delare, bit contrived), as well as messenger/communicator (meddelare). The word **Meddelare** represents both the count proxy as well as sharing button parts at the same time, don't you think?

**Done**

- Opened up accounts on:
  - github: https://github.com/meddelare/ @meddelare
  - npm: https://www.npmjs.com/~meddelare
  - twitter: https://twitter.com/meddelare
- Registered the domain name: http://meddelare.com/
- Created website: https://github.com/meddelare/meddelare.github.io
- Created gitslave superproject: https://github.com/meddelare/meddelare-superproject
- Split up the social-buttons-server code to separate projects and rebranded it.
  - Code: https://github.com/meddelare/meddelare-node-server
  - Examples: https://github.com/meddelare/meddelare-examples
- Applied the seven patches mentioned above, and a couple more.
- Published to Heroku: https://meddelare-node-server.herokuapp.com/?networks=facebook,twitter,googleplus&url=http://meddelare.com
- Added Meddelare Cloudfront: https://d12cncu17l9pr5.cloudfront.net/?networks=facebook,twitter,googleplus&url=http://meddelare.com

**Next steps**

- Create separate projects for the middleware and counter logic.
- Publish to npm.
- Get help creating a logotype and graphical profile.
- Get help adding pretty graphics to the website and examples.
- Get people to publish examples of their API usage/HTML widgets.
- **Get some shares, likes, +1s!** Looking at 0, 0, 0 gets boring after a while ;)

Conversations should continue in the Meddelare github projects, or on twitter. We can use the superproject for general discussions.

Thanks!
